# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ctp.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='ctp.proto',
  package='ctp',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\tctp.proto\x12\x03\x63tp\"\xba\x04\n\x0fTDF_FUTURE_DATA\x12\x12\n\nszwindcode\x18\x01 \x01(\t\x12\x15\n\rnauctionprice\x18\x1b \x01(\x05\x12\x13\n\x0bnauctionqty\x18\x1c \x01(\x05\x12\x0f\n\x07nstatus\x18\x06 \x01(\x05\x12\x0e\n\x06szcode\x18\x02 \x01(\t\x12\x12\n\nnactionday\x18\x03 \x01(\t\x12\x13\n\x0bntradingday\x18\x04 \x01(\t\x12\r\n\x05ntime\x18\x05 \x01(\x05\x12\x18\n\x10ipreopeninterest\x18\x07 \x01(\x01\x12\x11\n\tnpreclose\x18\x08 \x01(\x01\x12\x17\n\x0fnpresettleprice\x18\t \x01(\x01\x12\r\n\x05nopen\x18\n \x01(\x01\x12\r\n\x05nhigh\x18\x0b \x01(\x01\x12\x0c\n\x04nlow\x18\x0c \x01(\x01\x12\x0e\n\x06nmatch\x18\r \x01(\x01\x12\x0f\n\x07ivolume\x18\x0e \x01(\x05\x12\x11\n\titurnover\x18\x0f \x01(\x01\x12\x15\n\riopeninterest\x18\x10 \x01(\x01\x12\x0e\n\x06nclose\x18\x11 \x01(\x01\x12\x14\n\x0cnsettleprice\x18\x12 \x01(\x01\x12\x14\n\x0cnhighlimited\x18\x13 \x01(\x01\x12\x13\n\x0bnlowlimited\x18\x14 \x01(\x01\x12\x11\n\tnpredelta\x18\x15 \x01(\x01\x12\x12\n\nncurrdelta\x18\x16 \x01(\x01\x12\x11\n\tnaskprice\x18\x17 \x03(\x01\x12\x0f\n\x07naskvol\x18\x18 \x03(\x05\x12\x11\n\tnbidprice\x18\x19 \x03(\x01\x12\x0f\n\x07nbidvol\x18\x1a \x03(\x05\x12\x11\n\tnavgprice\x18\x1d \x01(\x01\x62\x06proto3')
)




_TDF_FUTURE_DATA = _descriptor.Descriptor(
  name='TDF_FUTURE_DATA',
  full_name='ctp.TDF_FUTURE_DATA',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='szwindcode', full_name='ctp.TDF_FUTURE_DATA.szwindcode', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='nauctionprice', full_name='ctp.TDF_FUTURE_DATA.nauctionprice', index=1,
      number=27, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='nauctionqty', full_name='ctp.TDF_FUTURE_DATA.nauctionqty', index=2,
      number=28, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='nstatus', full_name='ctp.TDF_FUTURE_DATA.nstatus', index=3,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='szcode', full_name='ctp.TDF_FUTURE_DATA.szcode', index=4,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='nactionday', full_name='ctp.TDF_FUTURE_DATA.nactionday', index=5,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ntradingday', full_name='ctp.TDF_FUTURE_DATA.ntradingday', index=6,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ntime', full_name='ctp.TDF_FUTURE_DATA.ntime', index=7,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ipreopeninterest', full_name='ctp.TDF_FUTURE_DATA.ipreopeninterest', index=8,
      number=7, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='npreclose', full_name='ctp.TDF_FUTURE_DATA.npreclose', index=9,
      number=8, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='npresettleprice', full_name='ctp.TDF_FUTURE_DATA.npresettleprice', index=10,
      number=9, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='nopen', full_name='ctp.TDF_FUTURE_DATA.nopen', index=11,
      number=10, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='nhigh', full_name='ctp.TDF_FUTURE_DATA.nhigh', index=12,
      number=11, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='nlow', full_name='ctp.TDF_FUTURE_DATA.nlow', index=13,
      number=12, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='nmatch', full_name='ctp.TDF_FUTURE_DATA.nmatch', index=14,
      number=13, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ivolume', full_name='ctp.TDF_FUTURE_DATA.ivolume', index=15,
      number=14, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='iturnover', full_name='ctp.TDF_FUTURE_DATA.iturnover', index=16,
      number=15, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='iopeninterest', full_name='ctp.TDF_FUTURE_DATA.iopeninterest', index=17,
      number=16, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='nclose', full_name='ctp.TDF_FUTURE_DATA.nclose', index=18,
      number=17, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='nsettleprice', full_name='ctp.TDF_FUTURE_DATA.nsettleprice', index=19,
      number=18, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='nhighlimited', full_name='ctp.TDF_FUTURE_DATA.nhighlimited', index=20,
      number=19, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='nlowlimited', full_name='ctp.TDF_FUTURE_DATA.nlowlimited', index=21,
      number=20, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='npredelta', full_name='ctp.TDF_FUTURE_DATA.npredelta', index=22,
      number=21, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ncurrdelta', full_name='ctp.TDF_FUTURE_DATA.ncurrdelta', index=23,
      number=22, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='naskprice', full_name='ctp.TDF_FUTURE_DATA.naskprice', index=24,
      number=23, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='naskvol', full_name='ctp.TDF_FUTURE_DATA.naskvol', index=25,
      number=24, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='nbidprice', full_name='ctp.TDF_FUTURE_DATA.nbidprice', index=26,
      number=25, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='nbidvol', full_name='ctp.TDF_FUTURE_DATA.nbidvol', index=27,
      number=26, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='navgprice', full_name='ctp.TDF_FUTURE_DATA.navgprice', index=28,
      number=29, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=19,
  serialized_end=589,
)

DESCRIPTOR.message_types_by_name['TDF_FUTURE_DATA'] = _TDF_FUTURE_DATA
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TDF_FUTURE_DATA = _reflection.GeneratedProtocolMessageType('TDF_FUTURE_DATA', (_message.Message,), dict(
  DESCRIPTOR = _TDF_FUTURE_DATA,
  __module__ = 'ctp_pb2'
  # @@protoc_insertion_point(class_scope:ctp.TDF_FUTURE_DATA)
  ))
_sym_db.RegisterMessage(TDF_FUTURE_DATA)


# @@protoc_insertion_point(module_scope)
